# Generated by Django 5.0.2 on 2024-02-19 07:41

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='buyyer',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='auto_active',
            new_name='automate_active',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='is_trade',
            new_name='is_active_month',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='views',
            new_name='watcher',
        ),
        migrations.RemoveField(
            model_name='post',
            name='favorites',
        ),
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='like_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'mp4', 'doc', 'docx'])]),
        ),
    ]
