# Generated by Django 5.0.2 on 2024-02-19 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
        ('store', '0002_rename_buyyer_chat_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='plan.plan'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='valuta_type',
            field=models.CharField(blank=True, choices=[('EURO', 'y.e'), ('SUM', 'Sum')], default='SUM', max_length=10, null=True),
        ),
    ]
