# Generated by Django 5.0.2 on 2024-02-19 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_alter_plandetail_code'),
        ('store', '0003_post_plan_alter_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='plan',
        ),
        migrations.AddField(
            model_name='post',
            name='PlanDetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='plan.plandetail'),
        ),
    ]
