# Generated by Django 5.0.2 on 2024-02-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandetail',
            name='code',
            field=models.CharField(blank=True, choices=[('VIP', 'Vip'), ('TOP', 'Top'), ('ABOVE', 'Above')], max_length=256, null=True),
        ),
    ]
